### ISSUE TITLE
Selection criteria for occurrences 

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/natagora-alien-occurrences#1]
A selection should be made based on the following criteria:

1. **Filter on the status of non-native species:**

category | status | details
--- | --- | ---
1b | Incidental / Vagrant / Migrant | Regular sightings in this country						
2a | Naturalized | Introduced by man, now autonomously reproducing						
2b | Naturalizing | Introduced by man, autonomous populations for 10-100 years.						
2c | Exotic | Introduced by man, no autonomous populations for more than 10 years.						
2d | Incidental import | Introduced by man, no autonomous population.	

2. **Filter on walloon observations:**

Two important questions:
1. Do all observations have a regional status provided for each of the provinces?  	
2. Do some observations only have national status information?

If option one is true, then all data can be obtained by filtering on observations from the walloon provinces `brabant wallon`, `hainaut`, `liège`, `luxembourg`, `namur`

3. **Filter on observations for which the observer did not object to the record being published**

This raw selection can be uploaded in the branch [upload-SQL-dump](https://github.com/trias-project/natagora-alien-occurrences/tree/upload-SQL-dump) where you can create a new folder `raw`.

**Comment by LouisNatagora** [comment]
To my eyes species of the category 1b are native. They should not be included.

**Comment by LouisNatagora** [comment]
About point 2: 
The majority of species only have one status for the whole Belgium. Only some of them have a status at province level that differs from the country one.

So, even if the option one is not true, one can filter on this information when it's available.

**Comment by peterdesmet** [comment]
@LouisNatagora I assume observation.be, waarnemingen.be, and waarneming.nl share the same species list? Can you confirm that?

If so, for step 1: the status of the species in Belgium is indicated in that list. You'll need to select the species with the status `naturalized`, `naturalizing`, `exotic`, or `incidental import`. There is not necessarily a need to filter further on the status within a province.

@karingielen @kristijnswinnen, can you confirm this is the way this is done for publishing non-native occurrences from waarnemingen.be?

**Comment by LouisNatagora** [comment]
@peterdesmet Yes observations.be, waarnemingen.be and waarneming.nl share the same species list. And yes a status for Belgium for each species is indicated for each species. O.K. we won't use status within province.

**Comment by peterdesmet** [comment]
Perfect! Than filter 1 will be exactly the same as Natuurpunt uses for publishing https://doi.org/10.15468/smdvdo and https://doi.org/10.15468/k2aiak

**Comment by LienReyserhove** [comment]
Sorry, my mistake, I misinterpreted the data, I was confused between the status of the population within the country/region and the status of the observation itself (presence in walloon region). So yes, of course the status for Belgium can be used
