### ISSUE TITLE
Getting DOI entry 

### ISSUE THREAD

**Issue by LouisNatagora** [trias-project/natagora-alien-occurrences#10]
Can you get me the DOI entry for URL https://ipt.biodiversity.be/resource?r=natagora-alien-occurrences ?
Thank you.

**Comment by peterdesmet** [comment]
Unfortunately the DOI is only known **after** publication. So we always publish a new version shortly after the first one, adding the DOI to the metadata and in the data (in datasetID). You can leave it empty for now.

**Comment by LouisNatagora** [comment]
I have published, but in Private mode. Do I need to make it public now? 
And then where will I get the DOI?

**Comment by peterdesmet** [comment]
That was a bit too fast. :smile: The order is public, publish, register, doi

But before you do, can we have a look at the data/metadata before final publication? You can add us a resource managers in the IPT (bottom of the page). Let us know if cannot find our user names.

**Comment by peterdesmet** [comment]
Seems @LienReyserhove has already access to that resource on the IPT. She will do a final check tomorrow.

**Comment by LienReyserhove** [comment]
See #12 for requested changes to the Natagora dataset

**Comment by LouisNatagora** [comment]
The ressource is currently being published...

**Comment by LouisNatagora** [comment]
Registered and DOIed!
Thank you all!

**Comment by LienReyserhove** [comment]
Could you please update the DOI with the full link, i.e. `https://doi.org/10.15468/p58ip1`?
This makes it easier for the data user to consult the dataset :-)
Thx!

**Comment by LouisNatagora** [comment]
Fixed. I did find where this was showed to control it...
