### ISSUE TITLE
Remove generalized records

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/natagora-alien-occurrences#11]
I know we discussed this issue before (and to be honest, I can't remember why we concluded to keep them in), but in hindsight, I believe we should remove the generalized records (those coordinates generalized to a 4x4km IFBL grid). This because:
1. The contract specifies that all records should be published as point records.
2. It only concerns 116 records

I also wonder why `georeferenceRemarks` is set to `coordinates are centroid of used grid square` for 2745 records. I suppose this is due to other reasons then to secrecy reasons?

**Comment by LouisNatagora** [comment]
There are in fact 2745 records. 

The 116 value is the result of a mistake I made (confusion between hiding the location and data not allowed to be published before a given date).  [By the way, fixing this important error will result in a slightly different total amount of data.]

2745 records out of 126477, that is 2%. 

You decide if I remove them or not.

**Comment by LouisNatagora** [comment]
After needed fixing total count is:
126368 : with generalized data
123720 : without "generalized data"
Difference is still 2%

**Comment by LouisNatagora** [comment]
I send both files  by WeTransfer.

**Comment by LienReyserhove** [comment]
I am still in favor of removing the generalized data, in line with my earlier comment

**Comment by LienReyserhove** [comment]
After discussing this with @peterdesmet, we do believe that the ca 3000 generalized records are a valuable addition to the dataset, so they can be included (very sorry for the confusion)

**Comment by LienReyserhove** [comment]
The current dataset published on GBIF is the one **without** generalized data. Could you please update the dataset with the 2648 generalized records? Also pay attention that this dataset has the datasetID field updated with the DOI :-)

**Comment by LouisNatagora** [comment]
You've got lynx eyes ;)
Fixed: generalized data are now present, along with the DOI as an URL for all sightings.
