### ISSUE TITLE
Complete README

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/natagora-alien-occurrences#13]
@LienReyserhove as per other datasets, can you complete the README for this datasets. I'm especially missing links to the dataset on IPT and GBIF.

I would also rename the `src` directory to `sql`

**Comment by LouisNatagora** [comment]
Oops... I didn't see you assigned this to @LienReyserhove 
I've done it... Please fix the README to fit your needs - it's maybe a little bit too technical.

**Comment by LienReyserhove** [comment]
I integrated some changes, see https://github.com/trias-project/natagora-alien-occurrences/pull/14
