### ISSUE TITLE
List of values for "Identification verification status"

### ISSUE THREAD

**Issue by LouisNatagora** [trias-project/natagora-alien-occurrences#2]
I need the list of the different possible values for field "Identification verification status". Where can I find it?

**Comment by peterdesmet** [comment]
Based on what we have with Natuurpunt, the values should be:

```
approved on expert judgement
approved on knowledge rules
approved on photographic evidence
unverified
```

I don't know the exact values in the source database, but i hope it is obvious.

**Comment by LouisNatagora** [comment]
Thank you
