### ISSUE TITLE
Why is there high coordinateUncertaintyInMeters

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/natagora-alien-occurrences#21]
2 questions:

1. Some (2%) of the records have "coordinates are generalized to a 4x4km IFBL grid". What is the reason for this?
2. For those records, the coordinateUncertaintyInMeters is 2828, but I'm also seeing higher values (e.g. 9363): where are these coming from?

**Comment by LouisNatagora** [comment]
1. In some cases observers do not give permission to share exact position of their sightings. In those cases the position of the center of the 4x4km IFBL square is used. The precision is then the larger distance from the center to any point of this square, that is the lenght of a mid-diagonal, sqrt(2^2+2^2).
2. Observers on observations.be can specify the precision of their data. This value is used for coordinateUncertaintyInMeters
