### ISSUE TITLE
Some entries have "migrating | seen" or "resting | seen" as samplingProtocol

### ISSUE THREAD

**Issue by LouisNatagora** [trias-project/natagora-alien-occurrences#27]
"migrating" and "resting" should go to behavior

**Comment by LouisNatagora** [comment]
@peterdesmet Where can I find the acceptable values for "behavior"? (Are "migrating" and "resting" acceptable values ?)

**Comment by peterdesmet** [comment]
These are all the accepted values: https://github.com/BelgianBiodiversityPlatform/natagora-occurrences/blob/master/references/behavior.csv `migrating` and `resting` are included.
