### ISSUE TITLE
Feedback on first_test_herpetology_one_user

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/natagora-alien-occurrences#3]
Thanks for this first data input. I browsed through the file, here are my remarks:

1. Presence of non-Dwc terms:

The following terms are not Darwin core terms:
- `typekid`
- `typeactid`
- `typemid`
- `act_occrem`
- `kleed_occrem`
- `met_occrem`
- `act_samplingprotocol`
- `met_samplingprotocol`

`typekid`, `typeactid` and `typemid` are the respective id's from database tables `type_kleed`, `type_activiteit` and `type_determination_method`.  These id's have been translated to a vocabulary for the mapping of the Darwin Core fields shown in the table below. The content of a Darwin Core term can be a compilation of id's from `type_kleed` and/or `type_activiteit` and/or `type_determination_method`, this is why `act_occrem`, `kleed_occrem`, `met_occrem`(for `occurrenceRemarks`), `act_samplingprotocol` and `met_samplingprotocol` (for `samplingProtocol`) have been created.

id | identificationRemarks | lifeStage | occurrenceRemarks | samplingProtocol | reproductiveCondition | behavior
--- | --- | --- | --- | --- | --- | ---
typekid | | x | x |  | x | | 
typeactid | | | x | x | | x |
typemid | x | | x | x | | |

2. accessRights: the current link [https://www.natagora.be/usage-des-donnees](https://www.natagora.be/usage-des-donnees) does not work (already discussed this)
 
3. There should be no dataGeneralizations in the datasets: all locations should be point coordinates and not generalized to a 5x5km UTM grid

4. decimalLatitude and decimalLongitude are not in the correct format. now valeus like `507098773` and `567654132843018` are present, should be something like `50.7098` and `5.6765`

**Comment by peterdesmet** [comment]
Small note on the coordinates: please use 5 decimals (always, even when 0).

**Comment by LouisNatagora** [comment]
Those points have been taken into account. Nevertheless, as discussed, I temporally readded the fields _TypeKid_, _typeActid_, _TypeMid_ to allow the checking of the values of the computated fields _occurrenceRemarks_ and _samplingProtocol_.

To give the lighter dataset possible I only selected one line from each combination of the fields _TypeKid_, _typeActid_, _TypeMid_ (along with their combination frequency as given by the count _nombre_cas_). Lines are ordered from most frequent to rarest combinations.

**Comment by LienReyserhove** [comment]
Closing issue, for an in-depth discussion on the fields typeKid, typeActid and typeKid, see #5 #6 and #7
