### ISSUE TITLE
reproductiveCondition

### ISSUE THREAD

**Issue by LouisNatagora** [trias-project/natagora-alien-occurrences#4]
This field (for which no documentation can be found on the web) only contains at present time
information from kleed : 'queen','worker','winged gyne' and 'unwinged gyne'	

I suggest we could also add to this field the following information that is now sent to other fields : 
1/ now sent to **behavior** : 'territorial behavior', 'copulating', 'laying egg', 'transporting feed or faeces', 'courtship/mating', 'nest building', 'distraction display', 
2/ now sent to **occurrenceRemarks** : 'adult in territory', 'near nest', 'colony in trees', 'colony','found as nest','occupied nest','occupied nest with eggs','occupied nest with young','with broodpatch','pair in territory','probably nesting place', 'recently hatched young', ''recently used nest', and also 'found as substrate with miner damage',  'found as gall','found as egg mass','found as cocoon'
and also 'abandoned nest'

Do you find it useful or unappropriate ?

**Comment by LienReyserhove** [comment]
Thanks for the input.
I can follow your arguments, I have thought this through and found it a very difficult exercise. 
I would approach it a bit differently though, and more in line with how the data was mapped for Natuurpunt. This is what I think:

1. reproductiveCondition: I would use this term to refer to the physiological state of the individual (or population)
2. behavior: all behavioral remarks, even those related to reproduction (but not the physiological state)
3. occurrenceRemarks: all other
4. Use a new term: lifeStage. We will probably need to translate this to a fixed vocabulary (young, egg,...)

What do you say?

Also: @peterdesmet: reproductiveCondition should have a fixed vocabulary (see [quick reference guide](http://rs.tdwg.org/dwc/terms/#dwc:reproductiveCondition)). I couldn't find on the [GBIF resources page](http://rs.gbif.org/vocabulary/) though...

reproductiveCondition | behavior | occurrenceRemarks | lifeStage
--- | --- | --- | ---
queen | territorial behavior | adult in territory | recently hatched young
worker | transporting feed or faeces | near nest | found as egg mass
winged gyne | nest buidling | colony in trees | found as cocoon
unwinged gyne | distraction display | colony | 
with broodpatch | copulating | found as nest | 
| | laying egg | occupied nest | 
| | courtship/mating | occupied nest with young | 
| | | pair in territory | 
| | | probably nesting place | 
| | | recently used nest | 
| | | found as substrate with miner damage | 
| | | found as gall | 
| | | abandoned nest |

**Comment by peterdesmet** [comment]
Indeed, there is no GBIF controlled vocabulary, so we made one for Natuurpunt datasets (in line with the Darwin Core examples). It indicates the reproductive state of the individual.

```
dead aboveground material
flowering
fruit-bearing
queen
reproductive
seedling
spore-bearing
sprouting
unwinged gyne
vegetative
winged gyne
worker
```

As there was no value for `pregnant` in the Natuurpunt datasets, we at first only used it for plant species. We later extended it to values for social insects (which also indicate their reproductive state).

One could argue to also include `breeding` (or lumping it in `reproductive`) in reproductiveCondition, deriving it from other values in behavior and occurrenceRemarks. For Natuurpunt datasets, we opted to just include the behavior and/or occurrenceRemarks, and not additionally map to reproductiveCondition.

**Comment by peterdesmet** [comment]
Note: I've uploaded the [controlled vocabularies we use for Natuurpunt datasets](https://github.com/trias-project/natagora-alien-occurrences/tree/master/references) for:

- samplingProtocol
- behavior
- lifeStage
- occurrenceRemarks
- reproductiveCondition

**Comment by LouisNatagora** [comment]
So I assume 

- "found as cocoon" gives "pupa" (in LifeStage)

- "found as egg mass" gives "egg"

**Comment by LouisNatagora** [comment]
As Peter said in a comment to another issue, "recently hatched young" is often selected by observers when they see both adults and young. 
Do I stay with this (and then use "Recently hatched young" in occurrenceRemarks) ?

**Comment by peterdesmet** [comment]
@LouisNatagora 

- `found as cocoon`: map as such in occurrenceRemarks + in addition, could be mapped as `pupa` in lifeStage (not done for Natuurpunt datasets, but would be good) 👌 
- `found as egg mass`: map as such in occurrenceRemarks + in addition, could be mapped as `egg` in lifeStage (not done for Natuurpunt datasets, but would be good) 👌 
- `recently hatched young`: map as such in occurrenceRemarks, no additional mapping required (so nothing in lifeStage)

**Comment by LouisNatagora** [comment]
Thank you for the controlled vocabulary. I suggest to add 'pregnant' to reproductiveCondition.
I added it for mammals (from typeAct).

**Comment by peterdesmet** [comment]
Didn’t see that value in the Natuurpunt data, but it’s perfectly valid value to add. 👌
