### ISSUE TITLE
Suggested changes for occurrenceRemarks

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/natagora-alien-occurrences#5]
I inspected the content of the current field `occurrenceRemarks`, a compilation of the information contained in `typeActid`, `typdeKid` and `typeMid`. Some suggestions for change:

occurrenceRemarks | decision | source | assign to new Darwin Core term
-- | -- | -- | --
recently hatched young | remove | typeActID| ~~lifeStage~~ leave in occurrenceRemarks
unknown | remove | typeActID| ~~?~~
indigenous | remove | typeActID| ~~establishmentMeans~~
present | remove | typeActID| ~~occurrenceStatus~~
occupied nest with eggs | remove | typeActID| ~~lifeStage~~ leave in occurrenceRemarks
adventive | remove | typeActID| ~~establishmentMeans (=introduced)~~, leave in occurrenceRemarks, but write as `accidentally introduced`
micr_examined_mat_present | remove | typeActID| ~~?~~ identificationRemarks( = `microscopic examination`)
catch_by_cat | remove | typeActID| leave in occurrenceRemarks, but write as `catch by cat`
washed_ashore | remove | typeActID| leave in occurrenceRemarks, but write as `washed ashore`
with broodpatch | remove | typeActID| ~~reproductiveStatus~~ leave in occurrenceRemarks, but write as `with brood patch`
microscopic_examined | remove | typeActID| ~~samplingProtocol~~ identificationRemarks( = `microscopic examination`)
seen while diving | remove | typeMid| samplingProtocol

**Comment by peterdesmet** [comment]
Reviewed table to have it in line with Natuurpunt datasets. Note that `recently hatched young` and `occupied nest with eggs` are not lifeStage, but a remark about the observed species (e.g. very often these remarks are about the parents)

**Comment by LouisNatagora** [comment]
Done.
