### ISSUE TITLE
suggested changes for samplingProtocol

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/natagora-alien-occurrences#6]
I inspected the content of the current field `samplingProtocol`, originally mapped from `typeActid`. Some suggestions for change:

samplingProtocol | decision | source | new Darwin Core term
-- | -- | -- | --
planted | remove | typeActID| occurrenceRemarks
unknown | remove | typeActID| ~~?~~
escaped | remove | typeActID| occurrenceRemarks
indigenous | remove | typeActID| ~~establishmentMeans~~
sown | remove | typeActID| occurrenceRemarks
present | remove | typeActID| ~~occurrenceStatus~~
adventive | remove | typeActID| ~~establishmentMeans~~: `accidentally introduced` in occurrenceRemarks
micr_examined_mat_present | remove | typeActID | ~~?~~: `microscopic examination` in identificationRemarks
catch_by_cat | remove | typeActID| occurrenceRemarks (= `catch by cat`)
washed_ashore | remove | typeActID| occurrenceRemarks (= `washed ashore`)

**Comment by peterdesmet** [comment]
I've updated the table above to be in line with Natuurpunt datasets

**Comment by LouisNatagora** [comment]
Already corrected following previous issues.

**Comment by LienReyserhove** [comment]
@peterdesmet  this table looks exactly the same as the one I posted, so presumably your updates were lost somewhere?

**Comment by peterdesmet** [comment]
Updated.
