### ISSUE TITLE
Suggested changes for behavior

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/natagora-alien-occurrences#7]
I inspected the content of the current field `behavior`, originally mapped from typeActid. Some suggestions for change:

behavior | decision | source | new Darwin Core term
-- | -- | -- | --
planted | remove | typeActID| occurrenceRemarks
escaped | remove | typeActID | occurrenceRemarks
indigenous | remove | typeActID | estblishmentMeans
sown | remove | typeActID | occurrenceRemarks
present | remove | typeActID | occurrenceStatus

**Comment by peterdesmet** [comment]
To be in line with Natuurpunt datasets:

- [ ] As you suggest, move `planted`, `escaped`, `sown` to `occurrenceRemarks`
- [ ] `present` is assumed, so do not map this value
- [ ] `indigenous` is filled out by the observer and often conflicting with the status of the species. We therefore do not populate `establishmentMeans`.

**Comment by LouisNatagora** [comment]
Done
