### ISSUE TITLE
Requested changes for behavior, occurrenceRemarks and samplingProtocol

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/natagora-alien-occurrences#8]
I went through the mapping of the following Darwin Core terms: `behavior`, `lifeStage`, `occurrenceRemarks`, `reproductiveCondition` and `samplingProtocol`. For the following terms, some adaptations are required to fit the [natuurpunt vocabularies](https://github.com/trias-project/natagora-alien-occurrences/tree/master/references):

### behavior
- `collected` is not integrated in the vocabulary for behavior and should be `NA` instead (thus `obsbe_act` = `COLLECTED` has no value for `behavior`)

### occurrenceRemarks
- `collected` is not integrated in the vocabulary for occurrenceRemarks and should be `NA` instead (thus `obsbe_act` = `COLLECTED` has no value for `occurrenceRemarks`)
- Use ` | ` as a separator for multiple values, rather then `;` (mark: there's a space before and after the hash)

### samplingPrototcol

- There's only one value allowed for `samplingProtocol`. Now, the field often contains a combination between `casual observation` and another sampling protocol. Instead, `casual observation` is the default value, used only when no alternatives are presented. This is why I suggest to map `obsbe_act` and `obsbe_method` directly to `samplingProtocol`, rather then joining the content of the intermediary columns `act_samplingProtocol` and `met_samplingProtocol`. The mapping should look like this (use a case_when statement):

obsbe_act | obsbe_method | samplingprotocol
-- | -- | --
CAMERATRAP | (...) | camera trap
CATCH | (...) | catch
CATCH_ELECTRIC | (...) | catch by electrofishing
CATCH_POLE | (...) | catch by fishing rod
CATCH_NET | (...) | catch by net
COLLECTED | (...) | specimen collected
WITH_DETECTORHUNTING | (...) | observation with bat detector
FLASHLIGHT_NIGHT_OBSERVATION | (...) | observation with flashlight
IN_PELLET | (...) | pellet examination
COLLECTED | (...) | specimen collected
(...) | BATDETECTOR | observation with bat detector
(...) | CAMERATRAP | camera trap
(...) | CAUGHT | catch
(...) | CAUGHT_ELECTRIC | catch by electrofishing
(...) | CAUGHT_BY_HAND | catch by hand
(...) | CAUGHT_BY_HAND_AND_COLLECTED | catch by hand and collected
(...) | CAUGHT_NET | catch by net
(...) | CAUGHT_POLE | catch by pole
(...) | BEATING_SCREEN | catch by screen
(...) | COLOURTRAP | colour trap
(...) | HEARD | heard
(...) | LIGHTTRAP | light trap
(...) | IN_PELLET | pellet examination
(...) | SEEN | seen
(...) | SEEN_AND_HEARD | seen and heard
(...) | INDOORS | seen indoors
(...) | SOUNDTRAPPED | sound trap
(...) | SPOTLIGHT_NIGHT_OBSERVATION | spotlight
(...) | TRACK_BED | track bed
(...) | (...) | casual observation

**Comment by LouisNatagora** [comment]
WITH_DETECTORHUNTING is used for other mammals than bats. I suggest as value for samplingprotocol "observation with detector". O.K.?

**Comment by peterdesmet** [comment]
Does WITH_DETECTORHUNTING imply the use of a **bat** detector, or are there other detectors? If so, best to use the already existing value `observation with bat detector`, otherwise `observation with detector` is ok.

**Comment by LouisNatagora** [comment]
WITH_DETECTORHUNTING does not imply anything about the detector. It can be a camera trap, a bat detector... There are sightings of Ovis orientalis musimon as well as of bats with this code (not proposed anymore to users, but we have to deal with old sightings too).
